export { default as Navbar } from './NavBar/Navbar'
export { default as Hero } from './Hero/Hero'
export { default as Banner } from './Banner/Banner'
export { default as Menu } from './Menu/Menu'
export { default as Hours } from './Hours/Hours'
export { default as Footer } from './Footer/Footer'
